import mongoose from "mongoose";

/**
 * Admin Schema - Civic Issue Reporting System
 * -----------------------------------------------------
 * The Admin model stores all information about the top-level
 * municipal system administrator(s) who manage:
 * - Users (citizens, ward reps, officers, workers)
 * - Wards and budgets
 * - Reports and analytics
 * - System configurations and logs
 */

const adminSchema = new mongoose.Schema(
  {
    // 🧍‍♂️ Base User Reference
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Admin must be linked to a user account"],
    },

    // ⚙️ Role-based privileges
    privileges: {
      type: [String],
      enum: [
        "manage_users",
        "manage_wards",
        "manage_budget",
        "view_reports",
        "approve_funds",
        "assign_officers",
        "generate_reports",
        "system_settings",
        "manage_notifications",
      ],
      default: [
        "manage_users",
        "manage_wards",
        "manage_budget",
        "view_reports",
        "approve_funds",
      ],
    },

    // 🏙️ Municipal Stats Overview
    stats: {
      totalWards: { type: Number, default: 0 },
      totalIssues: { type: Number, default: 0 },
      totalResolvedIssues: { type: Number, default: 0 },
      totalOfficers: { type: Number, default: 0 },
      totalWardReps: { type: Number, default: 0 },
      totalCitizens: { type: Number, default: 0 },
      totalWorkers: { type: Number, default: 0 },
      totalBudgetAllocated: { type: Number, default: 0 },
      totalBudgetUsed: { type: Number, default: 0 },
    },

    // 💰 Ward-level Budget Oversight
    wardBudgets: [
      {
        wardId: { type: mongoose.Schema.Types.ObjectId, ref: "Ward" },
        wardName: String,
        allocated: { type: Number, default: 0 },
        used: { type: Number, default: 0 },
        lastUpdated: { type: Date, default: Date.now },
      },
    ],

    // 🧾 Reports generated by the admin
    reportsGenerated: [
      {
        title: { type: String },
        description: { type: String },
        generatedAt: { type: Date, default: Date.now },
        reportType: {
          type: String,
          enum: ["monthly", "quarterly", "annual", "custom"],
          default: "custom",
        },
        fileUrl: { type: String },
      },
    ],

    // 🧠 System Configuration Settings
    settings: {
      systemName: {
        type: String,
        default: "Municipal Civic Issue Reporting System",
      },
      notificationEmail: {
        type: String,
        default: "support@municipal.gov.in",
      },
      alertThreshold: {
        type: Number,
        default: 80, // percent budget used before alert
      },
      theme: {
        type: String,
        enum: ["light", "dark"],
        default: "light",
      },
      allowCitizenComments: { type: Boolean, default: true },
      allowPublicFeed: { type: Boolean, default: true },
    },

    // 📊 Analytics Snapshots (For dashboard graphs)
    analytics: [
      {
        date: { type: Date, default: Date.now },
        totalIssues: Number,
        resolvedIssues: Number,
        budgetUsed: Number,
        topWard: String,
      },
    ],

    // 🪪 Officer and Representative Assignments
    wardAssignments: [
      {
        wardId: { type: mongoose.Schema.Types.ObjectId, ref: "Ward" },
        officerId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        repId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        assignedAt: { type: Date, default: Date.now },
      },
    ],

    // 🔔 Notifications / Announcements (broadcasts by admin)
    notifications: [
      {
        title: String,
        message: String,
        targetAudience: {
          type: String,
          enum: ["all", "officers", "reps", "citizens", "workers"],
          default: "all",
        },
        createdAt: { type: Date, default: Date.now },
        expiresAt: Date,
      },
    ],

    // 📜 System Activity Logs
    activityLogs: [
      {
        action: String,
        performedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        description: String,
        ipAddress: String,
        timestamp: { type: Date, default: Date.now },
      },
    ],

    // 🔐 Security Monitoring
    security: {
      lastLoginAt: Date,
      lastPasswordChange: Date,
      failedLoginAttempts: { type: Number, default: 0 },
      accountStatus: {
        type: String,
        enum: ["active", "suspended", "deactivated"],
        default: "active",
      },
    },

    // 🕒 Audit Timestamps
  },
  { timestamps: true }
);

export default mongoose.model("Admin", adminSchema);
